cd /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_003/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_003/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_003.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sleepyhead-flip-dual-sided-5-inch-queen-high-density-hd-foam-mattress\_fk_006/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sleepyhead-flip-dual-sided-5-inch-queen-high-density-hd-foam-mattress\_fk_006/sleepyhead-flip-dual-sided-5-inch-queen-high-density-hd-foam-mattress\_fk_006.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_013/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_013/beetel-x70-cordless-landline-phone\_fk_013.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_020/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_020/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_020.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch\_fk_028/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch\_fk_028/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch\_fk_028.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_147/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_147/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_147.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_000/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_000/beetel-x70-cordless-landline-phone\_fk_000.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_307/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_307/beetel-x70-cordless-landline-phone\_fk_307.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_412/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_412/beetel-x70-cordless-landline-phone\_fk_412.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_452/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_452/beetel-x70-cordless-landline-phone\_fk_452.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_494/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_494/beetel-x70-cordless-landline-phone\_fk_494.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_599/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_599/beetel-x70-cordless-landline-phone\_fk_599.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_607/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_607/beetel-x70-cordless-landline-phone\_fk_607.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_668/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_668/beetel-x70-cordless-landline-phone\_fk_668.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_723/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_723/beetel-x70-cordless-landline-phone\_fk_723.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_803/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_803/beetel-x70-cordless-landline-phone\_fk_803.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_023/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_023/beetel-x70-cordless-landline-phone\_fk_023.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_109/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone\_fk_109/beetel-x70-cordless-landline-phone\_fk_109.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron\_fk_289/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron\_fk_289/bajaj-mx-3-neo-1250-w-steam-iron\_fk_289.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/ambrane-10000-mah-22-5-w-wireless-magsafe-power-bank\_fk_836/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/ambrane-10000-mah-22-5-w-wireless-magsafe-power-bank\_fk_836/ambrane-10000-mah-22-5-w-wireless-magsafe-power-bank\_fk_836.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/havells-bt4441-trimmer-120-min-runtime-9-length-settings\_fk_641/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/havells-bt4441-trimmer-120-min-runtime-9-length-settings\_fk_641/havells-bt4441-trimmer-120-min-runtime-9-length-settings\_fk_641.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/bulkproduct/logitech-b175-optical-tracking-12-months-battery-life-ambidextrous-wireless-mouse\_fk_994/
sh /home/manish/puppeteer-scraper/flipkart_urls/bulkproduct/logitech-b175-optical-tracking-12-months-battery-life-ambidextrous-wireless-mouse\_fk_994/logitech-b175-optical-tracking-12-months-battery-life-ambidextrous-wireless-mouse\_fk_994.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/ariel-top-load-fresh-liquid-detergent\_fk_848/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/ariel-top-load-fresh-liquid-detergent\_fk_848/ariel-top-load-fresh-liquid-detergent\_fk_848.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_179/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_179/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_179.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb\_fk_620/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb\_fk_620/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb\_fk_620.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_366/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_366/crompton-75-l-desert-air-cooler\_fk_366.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-fabric-3-seater-sofa\_fk_423/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-fabric-3-seater-sofa\_fk_423/wakefit-fabric-3-seater-sofa\_fk_423.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa\_fk_573/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa\_fk_573/arra-remo-fabric-3-seater-sofa\_fk_573.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_900/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_900/wakefit-solatio-fabric-3-seater-sofa\_fk_900.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/oneplus-bullets-wireless-z2-bluetooth\_fk_789/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/oneplus-bullets-wireless-z2-bluetooth\_fk_789/oneplus-bullets-wireless-z2-bluetooth\_fk_789.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tp-link-tapo-c210-1296p-3mp-pan-tilt-home-wi-fi-smart-security-camera\_fk_357/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tp-link-tapo-c210-1296p-3mp-pan-tilt-home-wi-fi-smart-security-camera\_fk_357/tp-link-tapo-c210-1296p-3mp-pan-tilt-home-wi-fi-smart-security-camera\_fk_357.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/eveready-30-w-basic-standard-b22-led-bulb\_fk_586/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/eveready-30-w-basic-standard-b22-led-bulb\_fk_586/eveready-30-w-basic-standard-b22-led-bulb\_fk_586.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/eveready-30-w-basic-standard-b22-led-bulb\_fk_620/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/eveready-30-w-basic-standard-b22-led-bulb\_fk_620/eveready-30-w-basic-standard-b22-led-bulb\_fk_620.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_428/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_428/crompton-75-l-desert-air-cooler\_fk_428.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_543/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_543/crompton-75-l-desert-air-cooler\_fk_543.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_593/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_593/crompton-75-l-desert-air-cooler\_fk_593.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_712/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_712/crompton-75-l-desert-air-cooler\_fk_712.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-9-kg-5-star-ecobubble-wi-fi-digital-inverter-fully-automatic-top-load-washing-machine-grey\_fk_904/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-9-kg-5-star-ecobubble-wi-fi-digital-inverter-fully-automatic-top-load-washing-machine-grey\_fk_904/samsung-9-kg-5-star-ecobubble-wi-fi-digital-inverter-fully-automatic-top-load-washing-machine-grey\_fk_904.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_245/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_245/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_245.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_328/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_328/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_328.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_416/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_416/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_416.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_827/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_827/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_827.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_233/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_233/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_233.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_422/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_422/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_422.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_489/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_489/aristocrat-3p-set-cabin-medium-large-trolley-bag-cabin-check-in-8-wheels-30-inch\_fk_489.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/fastrack-68011pp08-tees-analog-watch-men\_fk_636/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/fastrack-68011pp08-tees-analog-watch-men\_fk_636/fastrack-68011pp08-tees-analog-watch-men\_fk_636.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/fastrack-68011pp08-tees-analog-watch-men\_fk_129/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/fastrack-68011pp08-tees-analog-watch-men\_fk_129/fastrack-68011pp08-tees-analog-watch-men\_fk_129.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/fastrack-68011pp08-tees-analog-watch-men\_fk_508/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/fastrack-68011pp08-tees-analog-watch-men\_fk_508/fastrack-68011pp08-tees-analog-watch-men\_fk_508.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/fastrack-68011pp08-tees-analog-watch-men\_fk_665/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/fastrack-68011pp08-tees-analog-watch-men\_fk_665/fastrack-68011pp08-tees-analog-watch-men\_fk_665.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5\_fk_112/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5\_fk_112/nivia-storm-pump-football-size-5\_fk_112.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_973/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_973/zebronics-jaguar-wireless-ambidextrous-optical-mouse-mouse-high-precision-4-buttons-plug-play\_fk_973.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker\_fk_798/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker\_fk_798/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker\_fk_798.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_234/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_234/crompton-75-l-desert-air-cooler\_fk_234.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5\_fk_277/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5\_fk_277/nivia-storm-pump-football-size-5\_fk_277.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb\_fk_289/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb\_fk_289/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb\_fk_289.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_300/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_300/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_300.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch\_fk_313/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch\_fk_313/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch\_fk_313.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_324/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_324/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_324.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth\_fk_333/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth\_fk_333/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth\_fk_333.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker\_fk_352/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker\_fk_352/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker\_fk_352.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_840/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_840/wakefit-solatio-fabric-3-seater-sofa\_fk_840.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa\_fk_929/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa\_fk_929/arra-remo-fabric-3-seater-sofa\_fk_929.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa\_fk_143/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa\_fk_143/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa\_fk_143.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa\_fk_253/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa\_fk_253/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa\_fk_253.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less_fk_760
sh /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less_fk_760/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less_fk_760.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less_fk_770
sh /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less_fk_770/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less_fk_770.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less_fk_779
sh /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less_fk_779/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less_fk_779.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_995/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_995/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_995.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_001/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_001/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_001.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_026/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_026/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_026.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_032/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_032/iffalcon-tcl-u65-138-cm-55-inch-ultra-hd-4k-led-smart-google-tv-2025-memc-dolby-vision-atmos-hva-panel-metallic-bezel-less\_fk_032.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_937/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_937/wakefit-solatio-fabric-3-seater-sofa\_fk_937.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_854/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_854/wakefit-solatio-fabric-3-seater-sofa\_fk_854.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_865/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_865/wakefit-solatio-fabric-3-seater-sofa\_fk_865.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_867/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_867/wakefit-solatio-fabric-3-seater-sofa\_fk_867.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_868/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_868/wakefit-solatio-fabric-3-seater-sofa\_fk_868.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_878/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_878/wakefit-solatio-fabric-3-seater-sofa\_fk_878.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_910/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa\_fk_910/wakefit-solatio-fabric-3-seater-sofa\_fk_910.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo\_fk_757/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo\_fk_757/tresemme-hairfall-defense-keratin-fillers-shampoo\_fk_757.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo\_fk_792/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo\_fk_792/tresemme-hairfall-defense-keratin-fillers-shampoo\_fk_792.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb\_fk_084/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb\_fk_084/vivo-t4x-5g-pronto-purple-256-gb\_fk_084.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb\_fk_/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb\_fk_/vivo-t4x-5g-pronto-purple-256-gb\_fk_.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb\_fk_/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb\_fk_/vivo-t4x-5g-pronto-purple-256-gb\_fk_.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb\_fk_/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb\_fk_/vivo-t4x-5g-pronto-purple-256-gb\_fk_.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb\_fk_/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb\_fk_/vivo-t4x-5g-pronto-purple-256-gb\_fk_.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER\_fk_/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER\_fk_/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER\_fk_.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-3-star-split-inverter-ac-white_ACNGYPU5FPG9ZSJM/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-3-star-split-inverter-ac-white_ACNGYPU5FPG9ZSJM/voltas-2024-model-1-5-ton-3-star-split-inverter-ac-white_ACNGYPU5FPG9ZSJM.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-5-star-split-inverter-ac-white_ACNGZEHFHENV5JYF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-5-star-split-inverter-ac-white_ACNGZEHFHENV5JYF/lloyd-1-5-ton-5-star-split-inverter-ac-white_ACNGZEHFHENV5JYF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/ifb-2025-model-silver-plus-series-1-5-ton-3-star-split-inverter-hd-compressor-ai-dual-gold-fin-nano-tek-coating-8-in-1-flexi-mode-ac-white_ACNH89DZMGW9QSWK/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/ifb-2025-model-silver-plus-series-1-5-ton-3-star-split-inverter-hd-compressor-ai-dual-gold-fin-nano-tek-coating-8-in-1-flexi-mode-ac-white_ACNH89DZMGW9QSWK/ifb-2025-model-silver-plus-series-1-5-ton-3-star-split-inverter-hd-compressor-ai-dual-gold-fin-nano-tek-coating-8-in-1-flexi-mode-ac-white_ACNH89DZMGW9QSWK.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/daikin-2023-model-1-5-ton-3-star-split-inverter-ac-pm-2-5-filter-white_ACNGFSYTSYRUQUSZ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/daikin-2023-model-1-5-ton-3-star-split-inverter-ac-pm-2-5-filter-white_ACNGFSYTSYRUQUSZ/daikin-2023-model-1-5-ton-3-star-split-inverter-ac-pm-2-5-filter-white_ACNGFSYTSYRUQUSZ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-3-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3W5YGCTSM/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-3-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3W5YGCTSM/marq-flipkart-2025-1-5-ton-3-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3W5YGCTSM.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-5-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3PR5JJ9YH/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-5-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3PR5JJ9YH/marq-flipkart-2025-1-5-ton-5-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3PR5JJ9YH.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXXMGGSGKR/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXXMGGSGKR/panasonic-2025-model-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXXMGGSGKR.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNH8EXUCPYYFZNG/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNH8EXUCPYYFZNG/godrej-2025-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNH8EXUCPYYFZNG.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZEGVGS5EE/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZEGVGS5EE/carrier-2025-model-6-1-convertible-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZEGVGS5EE.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZMUKYEEGP/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZMUKYEEGP/carrier-2025-model-6-1-convertible-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZMUKYEEGP.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-4-star-split-inverter-way-air-swing-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYWSEF847MT4Z/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-4-star-split-inverter-way-air-swing-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYWSEF847MT4Z/godrej-5-in-1-convertible-2024-model-1-5-ton-4-star-split-inverter-way-air-swing-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYWSEF847MT4Z.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-model-ai-convertible-6-in-1-1-5-ton-3-star-split-dual-inverter-faster-cooling-energy-saving-viraat-mode-diet-plus-ac-white_ACNH7SB8HTAJF85N/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-model-ai-convertible-6-in-1-1-5-ton-3-star-split-dual-inverter-faster-cooling-energy-saving-viraat-mode-diet-plus-ac-white_ACNH7SB8HTAJF85N/lg-2025-model-ai-convertible-6-in-1-1-5-ton-3-star-split-dual-inverter-faster-cooling-energy-saving-viraat-mode-diet-plus-ac-white_ACNH7SB8HTAJF85N.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXHDFAREWW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXHDFAREWW/panasonic-2025-model-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXHDFAREWW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-1-5-ton-4-star-split-inverter-ac-white_ACNH8NPZZTNZYYWX/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-1-5-ton-4-star-split-inverter-ac-white_ACNH8NPZZTNZYYWX/carrier-2025-model-1-5-ton-4-star-split-inverter-ac-white_ACNH8NPZZTNZYYWX.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-cooling-2024-model-1-5-ton-3-star-split-inverter-heavy-duty-extreme-temperature-ac-white_ACNHFAA4RZGFDABF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-cooling-2024-model-1-5-ton-3-star-split-inverter-heavy-duty-extreme-temperature-ac-white_ACNHFAA4RZGFDABF/godrej-5-in-1-convertible-cooling-2024-model-1-5-ton-3-star-split-inverter-heavy-duty-extreme-temperature-ac-white_ACNHFAA4RZGFDABF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYKCDQWYSX27Z/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYKCDQWYSX27Z/godrej-5-in-1-convertible-2024-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYKCDQWYSX27Z.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-5-star-split-inverter-ac-white_ACNGYPU5ASZ2TAYA/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-5-star-split-inverter-ac-white_ACNGYPU5ASZ2TAYA/voltas-2024-model-1-5-ton-5-star-split-inverter-ac-white_ACNGYPU5ASZ2TAYA.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPXC4HEZEY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPXC4HEZEY/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPXC4HEZEY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-3-star-split-inverter-ac-white_ACNGYXNMMHPSYNK5/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-3-star-split-inverter-ac-white_ACNGYXNMMHPSYNK5/lloyd-1-5-ton-3-star-split-inverter-ac-white_ACNGYXNMMHPSYNK5.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2024-model-7-1-convertible-true-ai-mode-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNGXYZYWHQVSGZT/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2024-model-7-1-convertible-true-ai-mode-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNGXYZYWHQVSGZT/panasonic-2024-model-7-1-convertible-true-ai-mode-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNGXYZYWHQVSGZT.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-5-in-1-convertible-cooling-1-5-ton-3-star-split-inverter-heavy-duty-pure-air-filter-ac-white_ACNH7SAZTYJ4JY3D/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-5-in-1-convertible-cooling-1-5-ton-3-star-split-inverter-heavy-duty-pure-air-filter-ac-white_ACNH7SAZTYJ4JY3D/godrej-2025-model-5-in-1-convertible-cooling-1-5-ton-3-star-split-inverter-heavy-duty-pure-air-filter-ac-white_ACNH7SAZTYJ4JY3D.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-windfree-technology-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPYKWRQPK9/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-windfree-technology-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPYKWRQPK9/samsung-2025-model-windfree-technology-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPYKWRQPK9.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-mode-ai-convertible-6-in-1-1-5-ton-5-star-split-dual-inverter-faster-cooling-energy-saving-4-way-air-swing-viraat-diet-plus-ac-white_ACNH7SB8EYTBFD2A/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-mode-ai-convertible-6-in-1-1-5-ton-5-star-split-dual-inverter-faster-cooling-energy-saving-4-way-air-swing-viraat-diet-plus-ac-white_ACNH7SB8EYTBFD2A/lg-2025-mode-ai-convertible-6-in-1-1-5-ton-5-star-split-dual-inverter-faster-cooling-energy-saving-4-way-air-swing-viraat-diet-plus-ac-white_ACNH7SB8EYTBFD2A.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-3-star-split-inverter-ac-white_ACNGYPU5FPG9ZSJM/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-3-star-split-inverter-ac-white_ACNGYPU5FPG9ZSJM/voltas-2024-model-1-5-ton-3-star-split-inverter-ac-white_ACNGYPU5FPG9ZSJM.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-5-star-split-inverter-ac-white_ACNGZEHFHENV5JYF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-5-star-split-inverter-ac-white_ACNGZEHFHENV5JYF/lloyd-1-5-ton-5-star-split-inverter-ac-white_ACNGZEHFHENV5JYF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/ifb-2025-model-silver-plus-series-1-5-ton-3-star-split-inverter-hd-compressor-ai-dual-gold-fin-nano-tek-coating-8-in-1-flexi-mode-ac-white_ACNH89DZMGW9QSWK/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/ifb-2025-model-silver-plus-series-1-5-ton-3-star-split-inverter-hd-compressor-ai-dual-gold-fin-nano-tek-coating-8-in-1-flexi-mode-ac-white_ACNH89DZMGW9QSWK/ifb-2025-model-silver-plus-series-1-5-ton-3-star-split-inverter-hd-compressor-ai-dual-gold-fin-nano-tek-coating-8-in-1-flexi-mode-ac-white_ACNH89DZMGW9QSWK.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/daikin-2023-model-1-5-ton-3-star-split-inverter-ac-pm-2-5-filter-white_ACNGFSYTSYRUQUSZ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/daikin-2023-model-1-5-ton-3-star-split-inverter-ac-pm-2-5-filter-white_ACNGFSYTSYRUQUSZ/daikin-2023-model-1-5-ton-3-star-split-inverter-ac-pm-2-5-filter-white_ACNGFSYTSYRUQUSZ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-3-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3W5YGCTSM/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-3-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3W5YGCTSM/marq-flipkart-2025-1-5-ton-3-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3W5YGCTSM.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-5-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3PR5JJ9YH/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-5-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3PR5JJ9YH/marq-flipkart-2025-1-5-ton-5-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3PR5JJ9YH.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXXMGGSGKR/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXXMGGSGKR/panasonic-2025-model-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXXMGGSGKR.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNH8EXUCPYYFZNG/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNH8EXUCPYYFZNG/godrej-2025-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNH8EXUCPYYFZNG.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZEGVGS5EE/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZEGVGS5EE/carrier-2025-model-6-1-convertible-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZEGVGS5EE.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZMUKYEEGP/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZMUKYEEGP/carrier-2025-model-6-1-convertible-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZMUKYEEGP.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-4-star-split-inverter-way-air-swing-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYWSEF847MT4Z/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-4-star-split-inverter-way-air-swing-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYWSEF847MT4Z/godrej-5-in-1-convertible-2024-model-1-5-ton-4-star-split-inverter-way-air-swing-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYWSEF847MT4Z.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-model-ai-convertible-6-in-1-1-5-ton-3-star-split-dual-inverter-faster-cooling-energy-saving-viraat-mode-diet-plus-ac-white_ACNH7SB8HTAJF85N/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-model-ai-convertible-6-in-1-1-5-ton-3-star-split-dual-inverter-faster-cooling-energy-saving-viraat-mode-diet-plus-ac-white_ACNH7SB8HTAJF85N/lg-2025-model-ai-convertible-6-in-1-1-5-ton-3-star-split-dual-inverter-faster-cooling-energy-saving-viraat-mode-diet-plus-ac-white_ACNH7SB8HTAJF85N.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXHDFAREWW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXHDFAREWW/panasonic-2025-model-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXHDFAREWW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-1-5-ton-4-star-split-inverter-ac-white_ACNH8NPZZTNZYYWX/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-1-5-ton-4-star-split-inverter-ac-white_ACNH8NPZZTNZYYWX/carrier-2025-model-1-5-ton-4-star-split-inverter-ac-white_ACNH8NPZZTNZYYWX.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-cooling-2024-model-1-5-ton-3-star-split-inverter-heavy-duty-extreme-temperature-ac-white_ACNHFAA4RZGFDABF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-cooling-2024-model-1-5-ton-3-star-split-inverter-heavy-duty-extreme-temperature-ac-white_ACNHFAA4RZGFDABF/godrej-5-in-1-convertible-cooling-2024-model-1-5-ton-3-star-split-inverter-heavy-duty-extreme-temperature-ac-white_ACNHFAA4RZGFDABF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYKCDQWYSX27Z/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYKCDQWYSX27Z/godrej-5-in-1-convertible-2024-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYKCDQWYSX27Z.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-5-star-split-inverter-ac-white_ACNGYPU5ASZ2TAYA/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-5-star-split-inverter-ac-white_ACNGYPU5ASZ2TAYA/voltas-2024-model-1-5-ton-5-star-split-inverter-ac-white_ACNGYPU5ASZ2TAYA.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPXC4HEZEY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPXC4HEZEY/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPXC4HEZEY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-3-star-split-inverter-ac-white_ACNGYXNMMHPSYNK5/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-3-star-split-inverter-ac-white_ACNGYXNMMHPSYNK5/lloyd-1-5-ton-3-star-split-inverter-ac-white_ACNGYXNMMHPSYNK5.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2024-model-7-1-convertible-true-ai-mode-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNGXYZYWHQVSGZT/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2024-model-7-1-convertible-true-ai-mode-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNGXYZYWHQVSGZT/panasonic-2024-model-7-1-convertible-true-ai-mode-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNGXYZYWHQVSGZT.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-5-in-1-convertible-cooling-1-5-ton-3-star-split-inverter-heavy-duty-pure-air-filter-ac-white_ACNH7SAZTYJ4JY3D/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-5-in-1-convertible-cooling-1-5-ton-3-star-split-inverter-heavy-duty-pure-air-filter-ac-white_ACNH7SAZTYJ4JY3D/godrej-2025-model-5-in-1-convertible-cooling-1-5-ton-3-star-split-inverter-heavy-duty-pure-air-filter-ac-white_ACNH7SAZTYJ4JY3D.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-windfree-technology-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPYKWRQPK9/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-windfree-technology-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPYKWRQPK9/samsung-2025-model-windfree-technology-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPYKWRQPK9.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-mode-ai-convertible-6-in-1-1-5-ton-5-star-split-dual-inverter-faster-cooling-energy-saving-4-way-air-swing-viraat-diet-plus-ac-white_ACNH7SB8EYTBFD2A/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-mode-ai-convertible-6-in-1-1-5-ton-5-star-split-dual-inverter-faster-cooling-energy-saving-4-way-air-swing-viraat-diet-plus-ac-white_ACNH7SB8EYTBFD2A/lg-2025-mode-ai-convertible-6-in-1-1-5-ton-5-star-split-dual-inverter-faster-cooling-energy-saving-4-way-air-swing-viraat-diet-plus-ac-white_ACNH7SB8EYTBFD2A.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-por-821-sounddrum-stereo-10-w-bluetooth-speaker_DHYFHFT2SSZGPAHB/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-por-821-sounddrum-stereo-10-w-bluetooth-speaker_DHYFHFT2SSZGPAHB/portronics-por-821-sounddrum-stereo-10-w-bluetooth-speaker_DHYFHFT2SSZGPAHB.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ/vivo-t4x-5g-pronto-purple-256-gb_MOBH9JUS4GGGPJHJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-3-star-split-inverter-ac-white_ACNGYPU5FPG9ZSJM/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-3-star-split-inverter-ac-white_ACNGYPU5FPG9ZSJM/voltas-2024-model-1-5-ton-3-star-split-inverter-ac-white_ACNGYPU5FPG9ZSJM.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-5-star-split-inverter-ac-white_ACNGZEHFHENV5JYF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-5-star-split-inverter-ac-white_ACNGZEHFHENV5JYF/lloyd-1-5-ton-5-star-split-inverter-ac-white_ACNGZEHFHENV5JYF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/ifb-2025-model-silver-plus-series-1-5-ton-3-star-split-inverter-hd-compressor-ai-dual-gold-fin-nano-tek-coating-8-in-1-flexi-mode-ac-white_ACNH89DZMGW9QSWK/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/ifb-2025-model-silver-plus-series-1-5-ton-3-star-split-inverter-hd-compressor-ai-dual-gold-fin-nano-tek-coating-8-in-1-flexi-mode-ac-white_ACNH89DZMGW9QSWK/ifb-2025-model-silver-plus-series-1-5-ton-3-star-split-inverter-hd-compressor-ai-dual-gold-fin-nano-tek-coating-8-in-1-flexi-mode-ac-white_ACNH89DZMGW9QSWK.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/daikin-2023-model-1-5-ton-3-star-split-inverter-ac-pm-2-5-filter-white_ACNGFSYTSYRUQUSZ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/daikin-2023-model-1-5-ton-3-star-split-inverter-ac-pm-2-5-filter-white_ACNGFSYTSYRUQUSZ/daikin-2023-model-1-5-ton-3-star-split-inverter-ac-pm-2-5-filter-white_ACNGFSYTSYRUQUSZ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-3-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3W5YGCTSM/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-3-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3W5YGCTSM/marq-flipkart-2025-1-5-ton-3-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3W5YGCTSM.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-5-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3PR5JJ9YH/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-2025-1-5-ton-5-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3PR5JJ9YH/marq-flipkart-2025-1-5-ton-5-star-split-inverter-5-in-1-convertible-turbo-cool-technology-ac-white_ACNH76Z3PR5JJ9YH.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXXMGGSGKR/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXXMGGSGKR/panasonic-2025-model-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXXMGGSGKR.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNH8EXUCPYYFZNG/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNH8EXUCPYYFZNG/godrej-2025-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNH8EXUCPYYFZNG.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZEGVGS5EE/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZEGVGS5EE/carrier-2025-model-6-1-convertible-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZEGVGS5EE.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZMUKYEEGP/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-6-1-convertible-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZMUKYEEGP/carrier-2025-model-6-1-convertible-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8NPZMUKYEEGP.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-4-star-split-inverter-way-air-swing-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYWSEF847MT4Z/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-4-star-split-inverter-way-air-swing-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYWSEF847MT4Z/godrej-5-in-1-convertible-2024-model-1-5-ton-4-star-split-inverter-way-air-swing-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYWSEF847MT4Z.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-model-ai-convertible-6-in-1-1-5-ton-3-star-split-dual-inverter-faster-cooling-energy-saving-viraat-mode-diet-plus-ac-white_ACNH7SB8HTAJF85N/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-model-ai-convertible-6-in-1-1-5-ton-3-star-split-dual-inverter-faster-cooling-energy-saving-viraat-mode-diet-plus-ac-white_ACNH7SB8HTAJF85N/lg-2025-model-ai-convertible-6-in-1-1-5-ton-3-star-split-dual-inverter-faster-cooling-energy-saving-viraat-mode-diet-plus-ac-white_ACNH7SB8HTAJF85N.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXHDFAREWW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2025-model-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXHDFAREWW/panasonic-2025-model-1-5-ton-5-star-split-inverter-ac-wi-fi-connect-white_ACNH8EYXHDFAREWW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-1-5-ton-4-star-split-inverter-ac-white_ACNH8NPZZTNZYYWX/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/carrier-2025-model-1-5-ton-4-star-split-inverter-ac-white_ACNH8NPZZTNZYYWX/carrier-2025-model-1-5-ton-4-star-split-inverter-ac-white_ACNH8NPZZTNZYYWX.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-cooling-2024-model-1-5-ton-3-star-split-inverter-heavy-duty-extreme-temperature-ac-white_ACNHFAA4RZGFDABF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-cooling-2024-model-1-5-ton-3-star-split-inverter-heavy-duty-extreme-temperature-ac-white_ACNHFAA4RZGFDABF/godrej-5-in-1-convertible-cooling-2024-model-1-5-ton-3-star-split-inverter-heavy-duty-extreme-temperature-ac-white_ACNHFAA4RZGFDABF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYKCDQWYSX27Z/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-5-in-1-convertible-2024-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYKCDQWYSX27Z/godrej-5-in-1-convertible-2024-model-1-5-ton-5-star-split-inverter-heavy-duty-cooling-extreme-temperature-ac-white_ACNGYKCDQWYSX27Z.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-5-star-split-inverter-ac-white_ACNGYPU5ASZ2TAYA/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/voltas-2024-model-1-5-ton-5-star-split-inverter-ac-white_ACNGYPU5ASZ2TAYA/voltas-2024-model-1-5-ton-5-star-split-inverter-ac-white_ACNGYPU5ASZ2TAYA.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPXC4HEZEY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPXC4HEZEY/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPXC4HEZEY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-3-star-split-inverter-ac-white_ACNGYXNMMHPSYNK5/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lloyd-1-5-ton-3-star-split-inverter-ac-white_ACNGYXNMMHPSYNK5/lloyd-1-5-ton-3-star-split-inverter-ac-white_ACNGYXNMMHPSYNK5.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2024-model-7-1-convertible-true-ai-mode-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNGXYZYWHQVSGZT/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/panasonic-2024-model-7-1-convertible-true-ai-mode-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNGXYZYWHQVSGZT/panasonic-2024-model-7-1-convertible-true-ai-mode-1-5-ton-3-star-split-inverter-ac-wi-fi-connect-white_ACNGXYZYWHQVSGZT.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-5-in-1-convertible-cooling-1-5-ton-3-star-split-inverter-heavy-duty-pure-air-filter-ac-white_ACNH7SAZTYJ4JY3D/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/godrej-2025-model-5-in-1-convertible-cooling-1-5-ton-3-star-split-inverter-heavy-duty-pure-air-filter-ac-white_ACNH7SAZTYJ4JY3D/godrej-2025-model-5-in-1-convertible-cooling-1-5-ton-3-star-split-inverter-heavy-duty-pure-air-filter-ac-white_ACNH7SAZTYJ4JY3D.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-windfree-technology-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPYKWRQPK9/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-windfree-technology-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPYKWRQPK9/samsung-2025-model-windfree-technology-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPYKWRQPK9.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-mode-ai-convertible-6-in-1-1-5-ton-5-star-split-dual-inverter-faster-cooling-energy-saving-4-way-air-swing-viraat-diet-plus-ac-white_ACNH7SB8EYTBFD2A/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lg-2025-mode-ai-convertible-6-in-1-1-5-ton-5-star-split-dual-inverter-faster-cooling-energy-saving-4-way-air-swing-viraat-diet-plus-ac-white_ACNH7SB8EYTBFD2A/lg-2025-mode-ai-convertible-6-in-1-1-5-ton-5-star-split-dual-inverter-faster-cooling-energy-saving-4-way-air-swing-viraat-diet-plus-ac-white_ACNH7SB8EYTBFD2A.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA/wakefit-solatio-fabric-3-seater-sofa_SOFGJVQY5RXF5HCA.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist/nivia-storm-pump-football-size-5_BALGT7YTWAHUN4EY&otracker=wishlist.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist/crompton-75-l-desert-air-cooler_AICEQGBHB75HSWGG&otracker=wishlist.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs_SMPGEA3W6VFBYZ8B.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch_STCFSDZ67ZMVMKYY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM/bajaj-mx-3-neo-1250-w-steam-iron_IRNGBWZGWSBPDZAM.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ/tresemme-keratin-smooth-shampoo_SMPFC62BFAN9MYGJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN/samsung-2025-model-bespoke-ai-5-step-convertible-1-5-ton-3-star-split-inverter-powerful-cooling-energy-saving-120-expandable-ac-wi-fi-connect-white_ACNH7SAPGZZCDTDN.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER/tresemme-hairfall-defense-keratin-fillers-shampoo_SMPFC62BNCVZHZER.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS/avita-domus-10w-led-5ch-rgb-smart-bulb_LLSGF5H4PCYD7HUS.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF/boat-rockerz-110-40-hrs-playback-enx-technology-beast-mode-asap-charge-bluetooth_ACCGS9ZMGQZH4FZF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ/portronics-1-10w-tws-portable-type-c-charging-10-w-bluetooth-speaker_ACCG43UYES5YAHMJ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF/evm-128gb-sata-ssd-128-gb-all-one-pc-s-desktop-laptop-black-internal-solid-state-drive-ssd-25-128gb_IHDHF85GTUFMZAAF.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY/seventh-heaven-tokyo-3-seater-sofa-extra-spacious-chenille-molfino-fabric-2-year-warranty-fabric-sofa_SOFGY3QK2TF4MJMY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY/arra-remo-fabric-3-seater-sofa_SOFH7Z9GEPXNWUYY.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW/sandisk-e61-1050-mbs-window-mac-os-android-portable-type-c-enabled-5-y-warranty-usb-3-2-1-tb-wired-external-solid-state-drive-ssd_ACCGYSPEYXV2EUPW.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/cmf-nothing-phone-1-black-128-gb_MOBHYBQTSE9EKVBT/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/cmf-nothing-phone-1-black-128-gb_MOBHYBQTSE9EKVBT/cmf-nothing-phone-1-black-128-gb_MOBHYBQTSE9EKVBT.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone_LANEH8G46KS9CSND/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/beetel-x70-cordless-landline-phone_LANEH8G46KS9CSND/beetel-x70-cordless-landline-phone_LANEH8G46KS9CSND.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/dream-care-fitted-queen-size-breathable-stretchable-waterproof-mattress-cover_MTPF8AAZZZHC4GW6/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/dream-care-fitted-queen-size-breathable-stretchable-waterproof-mattress-cover_MTPF8AAZZZHC4GW6/dream-care-fitted-queen-size-breathable-stretchable-waterproof-mattress-cover_MTPF8AAZZZHC4GW6.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/mattress-protector-fitted-queen-size-breathable-stretchable-waterproof-cover_MTPG7QVYRNVEHHV5/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/mattress-protector-fitted-queen-size-breathable-stretchable-waterproof-cover_MTPG7QVYRNVEHHV5/mattress-protector-fitted-queen-size-breathable-stretchable-waterproof-cover_MTPG7QVYRNVEHHV5.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/cmf-nothing-phone-2-pro-light-green-128-gb_MOBHAUHADASAEX2G/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/cmf-nothing-phone-2-pro-light-green-128-gb_MOBHAUHADASAEX2G/cmf-nothing-phone-2-pro-light-green-128-gb_MOBHAUHADASAEX2G.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/cmf-nothing-phone-2-pro-black-256-gb_MOBHAUHAY7BY7PT5/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/cmf-nothing-phone-2-pro-black-256-gb_MOBHAUHAY7BY7PT5/cmf-nothing-phone-2-pro-black-256-gb_MOBHAUHAY7BY7PT5.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/arctic-fox-pureview-transparent-wireless-bluetooth-rechargeable-mouse-optical-gaming_ACCGVUZSNYH8PS2G/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/arctic-fox-pureview-transparent-wireless-bluetooth-rechargeable-mouse-optical-gaming_ACCGVUZSNYH8PS2G/arctic-fox-pureview-transparent-wireless-bluetooth-rechargeable-mouse-optical-gaming_ACCGVUZSNYH8PS2G.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/arctic-fox-pureview-transparent-wireless-bluetooth-rechargeable-mouse-optical-gaming_ACCGVUZSNYH8PS2G/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/arctic-fox-pureview-transparent-wireless-bluetooth-rechargeable-mouse-optical-gaming_ACCGVUZSNYH8PS2G/arctic-fox-pureview-transparent-wireless-bluetooth-rechargeable-mouse-optical-gaming_ACCGVUZSNYH8PS2G.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/realme-buds-wireless-5-50db-anc-360-degree-spatial-audio-ip55-38hrs-playback-bluetooth_ACCH6SR8NYS7A3ZR/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/realme-buds-wireless-5-50db-anc-360-degree-spatial-audio-ip55-38hrs-playback-bluetooth_ACCH6SR8NYS7A3ZR/realme-buds-wireless-5-50db-anc-360-degree-spatial-audio-ip55-38hrs-playback-bluetooth_ACCH6SR8NYS7A3ZR.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/realme-buds-wireless-5-50db-anc-360-degree-spatial-audio-ip55-38hrs-playback-bluetooth_ACCH6SR8NYS7A3ZR/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/realme-buds-wireless-5-50db-anc-360-degree-spatial-audio-ip55-38hrs-playback-bluetooth_ACCH6SR8NYS7A3ZR/realme-buds-wireless-5-50db-anc-360-degree-spatial-audio-ip55-38hrs-playback-bluetooth_ACCH6SR8NYS7A3ZR.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/ariel-top-load-fresh-liquid-detergent_LDGGXAU7RW9P3HHT/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/ariel-top-load-fresh-liquid-detergent_LDGGXAU7RW9P3HHT/ariel-top-load-fresh-liquid-detergent_LDGGXAU7RW9P3HHT.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/ariel-top-load-fresh-liquid-detergent_LDGGKZAVW2GBJQ6W/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/ariel-top-load-fresh-liquid-detergent_LDGGKZAVW2GBJQ6W/ariel-top-load-fresh-liquid-detergent_LDGGKZAVW2GBJQ6W.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-toad-5-transparent-wireless-mouse-bluetooth-2-4-ghz-rechargeable-rgb-light-ambidextrous-optical-mouse_ACCH2GB9HZH9YJK8/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/portronics-toad-5-transparent-wireless-mouse-bluetooth-2-4-ghz-rechargeable-rgb-light-ambidextrous-optical-mouse_ACCH2GB9HZH9YJK8/portronics-toad-5-transparent-wireless-mouse-bluetooth-2-4-ghz-rechargeable-rgb-light-ambidextrous-optical-mouse_ACCH2GB9HZH9YJK8.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/themisto-th-tds10-digital-tds-meter_TDSG5D778QCGRJZ5/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/themisto-th-tds10-digital-tds-meter_TDSG5D778QCGRJZ5/themisto-th-tds10-digital-tds-meter_TDSG5D778QCGRJZ5.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/themisto-th-tds10-digital-tds-meter_TDSG5D778QCGRJZ5/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/themisto-th-tds10-digital-tds-meter_TDSG5D778QCGRJZ5/themisto-th-tds10-digital-tds-meter_TDSG5D778QCGRJZ5.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-90-l-direct-cool-single-door-1-star-refrigerator-super-chill-zone-toughened-glass-shelves_RFRGZT6EYBDDCPKQ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/marq-flipkart-90-l-direct-cool-single-door-1-star-refrigerator-super-chill-zone-toughened-glass-shelves_RFRGZT6EYBDDCPKQ/marq-flipkart-90-l-direct-cool-single-door-1-star-refrigerator-super-chill-zone-toughened-glass-shelves_RFRGZT6EYBDDCPKQ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-25-w-gan-3-wall-charger-mobile_ACCHYG6CVZEARUWZ/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/samsung-25-w-gan-3-wall-charger-mobile_ACCHYG6CVZEARUWZ/samsung-25-w-gan-3-wall-charger-mobile_ACCHYG6CVZEARUWZ.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/urbn-20-w-gan-3-wall-charger-mobile_ACCGWKD6TZJF4WGR/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/urbn-20-w-gan-3-wall-charger-mobile_ACCGWKD6TZJF4WGR/urbn-20-w-gan-3-wall-charger-mobile_ACCGWKD6TZJF4WGR.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/lenovo-chromebook-duet-11m889-mediatek-kompanio-838-8-gb-128-gb-emmc-storage-chrome-os_COMHBCAFZGVNEDTK&fm=organic&ppt=dynamic&ppn=dynamic&ssid=k72kthd0yo0000001755169469149/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/lenovo-chromebook-duet-11m889-mediatek-kompanio-838-8-gb-128-gb-emmc-storage-chrome-os_COMHBCAFZGVNEDTK&fm=organic&ppt=dynamic&ppn=dynamic&ssid=k72kthd0yo0000001755169469149/lenovo-chromebook-duet-11m889-mediatek-kompanio-838-8-gb-128-gb-emmc-storage-chrome-os_COMHBCAFZGVNEDTK&fm=organic&ppt=dynamic&ppn=dynamic&ssid=k72kthd0yo0000001755169469149.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/cmf-nothing-33-w-quick-charge-3-wall-charger-mobile_ACCH28GD4NZMZFAE/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/cmf-nothing-33-w-quick-charge-3-wall-charger-mobile_ACCH28GD4NZMZFAE/cmf-nothing-33-w-quick-charge-3-wall-charger-mobile_ACCH28GD4NZMZFAE.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/urbn-10000-mah-22-5-w-power-bank_PWBHBCHYXH7ZTXHH/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/urbn-10000-mah-22-5-w-power-bank_PWBHBCHYXH7ZTXHH/urbn-10000-mah-22-5-w-power-bank_PWBHBCHYXH7ZTXHH.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/cmf-nothing-65-w-gan-3-port-mobile-charger_ACCGPU7G7SSEYCGS/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/cmf-nothing-65-w-gan-3-port-mobile-charger_ACCGPU7G7SSEYCGS/cmf-nothing-65-w-gan-3-port-mobile-charger_ACCGPU7G7SSEYCGS.sh
