cd /home/manish/puppeteer-scraper/flipkart_urls/products/mi-10000-mah-22-5-w-power-bank\_fk_057/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/mi-10000-mah-22-5-w-power-bank\_fk_057/mi-10000-mah-22-5-w-power-bank\_fk_057.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_539/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/crompton-75-l-desert-air-cooler\_fk_539/crompton-75-l-desert-air-cooler\_fk_539.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/nilkamal-indio-engineered-wood-2-door-wardrobe\_fk_654/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/nilkamal-indio-engineered-wood-2-door-wardrobe\_fk_654/nilkamal-indio-engineered-wood-2-door-wardrobe\_fk_654.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron\_fk_814/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/bajaj-mx-3-neo-1250-w-steam-iron\_fk_814/bajaj-mx-3-neo-1250-w-steam-iron\_fk_814.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-colorbst-sp55pgrn-cabin-suitcase-4-wheels-22-inch\_fk_873/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-colorbst-sp55pgrn-cabin-suitcase-4-wheels-22-inch\_fk_873/kamiliant-american-tourister-kam-triprism-colorbst-sp55pgrn-cabin-suitcase-4-wheels-22-inch\_fk_873.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch\_fk_026/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch\_fk_026/kamiliant-american-tourister-kam-triprism-sp-aqua-check-in-suitcase-4-wheels-27-inch\_fk_026.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-cabin-suitcase-4-wheels-22-inch\_fk_065/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kamiliant-american-tourister-kam-triprism-sp-aqua-cabin-suitcase-4-wheels-22-inch\_fk_065/kamiliant-american-tourister-kam-triprism-sp-aqua-cabin-suitcase-4-wheels-22-inch\_fk_065.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_399/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_399/kesh-king-ayurvedic-anti-hairfall-shampoo-enriched-aloe-21-herbs\_fk_399.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo\_fk_528/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/tresemme-hairfall-defense-keratin-fillers-shampoo\_fk_528/tresemme-hairfall-defense-keratin-fillers-shampoo\_fk_528.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/havells-fabio-1250-w-steam-iron\_fk_663/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/havells-fabio-1250-w-steam-iron\_fk_663/havells-fabio-1250-w-steam-iron\_fk_663.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_267/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_267/avita-domus-10w-led-5ch-rgb-smart-bulb\_fk_267.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/v-guard-50-l-tower-air-cooler\_fk_011/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/v-guard-50-l-tower-air-cooler\_fk_011/v-guard-50-l-tower-air-cooler\_fk_011.sh
cd /home/manish/puppeteer-scraper/flipkart_urls/products/v-guard-50-l-tower-air-cooler\_fk_279/
sh /home/manish/puppeteer-scraper/flipkart_urls/products/v-guard-50-l-tower-air-cooler\_fk_279/v-guard-50-l-tower-air-cooler\_fk_279.sh
